### ISSUE TITLE
Upgrading quil to 3.0.0 seems to break the demo. 

### ISSUE THREAD

**Issue by samirsa** [yogthos/quil-reagent-demo#1]
Hello, 
I was using this repo (thanks for all the awesome work!) to create a starter reagent+quil project. It seemed to work well, with the quil (2.7.1)  

However, when I upgrade to the latest quil version of 3.0.0 (or even 3.1.0-SNAPSHOT), the setup does not work. 

The only difference from this and the other quil-template demo (from the quil repo) seems to be the use of the host node - Using the component instead of a div id. 

```
(defn canvas []
  (r/create-class
    {:component-did-mount
     (fn [component]
       (let [node (r/dom-node component)
             width (.-width node)
             height (.-height node)]
         (q/sketch
           :host node
           :draw draw
           :setup (init width height)
           :update update-state
           :size [width height]
           :middleware [m/fun-mode])))
     :render
     (fn []
       [:canvas {:width  (/ (.-innerWidth js/window) 2)
                 :height (/ (.-innerHeight js/window) 2)}])}))
```

I tried creating a new reagent project (not using the quil-reagent-demo linked up), and tried to add a quil sketch to it. The results seemed the same - where if I link to the div id, then it shows up, but I would like to link it to a component (so that it can be controlled via the reagent framework - displayed moved etc.) 

PS - I am slightly new to the reagent/quil world of clojurescript, and might be making a noob mistake. 

thanks in advance.

**Comment by samirsa** [comment]
It seems the recent versions of quil - create or append a canvas to an existing canvas and that was causing the problem. 
Changing it to the following to render a new div instead of a Canvas, seems to have fixed it. 

```
     :render
     (fn []
       [:div ])}))
```

**Comment by yogthos** [comment]
Thanks for the heads up, I've updated the example in the repo.
